[build]
# Install Node.js
providers = ["node"]

[build.node]
version = "20"

[build.cmd]
install = "npm install"
build = "npx prisma generate && npx tsc"

[deploy]
cmd = "npx prisma migrate deploy && node dist/server.js"
